### ISSUE TITLE
Add json example for nested object in the doc

### ISSUE THREAD

**Issue by zodd3131** [arkmq-org/activemq-artemis-operator#1070]
**Describe the feature**
A new feature has been added that provides the ability to pass broker.properties through a json secret.
ActiveMQArtemisSecurity is now a deprecated resource and it's now recommanded to provide configuration with spec.brokerProperties. I would like to implement what it is described here : [providing-additional-brokerproperties-configuration-from-a-secret)](https://artemiscloud.io/docs/help/operator/#providing-additional-brokerproperties-configuration-from-a-secret).
How to write nested object and what to escape as characters?
How to translate the yaml below into a json secret?

```yaml
securitySettings:
    broker:
      - match: "app.europe.#"
        permissions:
          - operationType: createNonDurableQueue
            roles: ["admin"]
          - operationType: deleteNonDurableQueue
            roles: ["admin"]
          - operationType: createDurableQueue
            roles: ["admin"]
          - operationType: deleteDurableQueue
            roles: ["admin"]
          - operationType: createAddress
            roles: ["admin"]
          - operationType: deleteAddress
            roles: ["admin"]
          - operationType: createAddress
            roles: ["admin"]
          - operationType: consume
            roles: ["admin", "guest"]
          - operationType: send
            roles: ["admin"]
```

I would like to complete the documentation with more complex examples.
> [!TIP]
> Vote this issue reacting with :+1: or :-1:

**Comment by brusdev** [comment]
@zodd3131 you can convert security settings of ActiveMQArtemisSecurity CR to broker properties ActiveMQArtemis CR, .i.e.
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
spec:
  brokerProperties:
    - 'securityRoles."app.europe.#".admin.createNonDurableQueue=true'
    - 'securityRoles."app.europe.#".admin.deleteNonDurableQueue=true'
    - 'securityRoles."app.europe.#".admin.createDurableQueue=true'
    - 'securityRoles."app.europe.#".admin.deleteDurableQueue=false'
    - 'securityRoles."app.europe.#".admin.createAddress=false'
    - 'securityRoles."app.europe.#".admin.deleteAddress=false'
    - 'securityRoles."app.europe.#".admin.consume=false'
    - 'securityRoles."app.europe.#".admin.send=false'
```
