### ISSUE TITLE
Admin password using k8s secret ref

### ISSUE THREAD

**Issue by jespernylendklp** [arkmq-org/activemq-artemis-operator#1077]
**Describe the feature**
Admin password is today supported via the `.spec.adminPassword` field on the ActiveMQArtemis CRD. This field only takes in a string, which would render the admin password in clear text for those that have access to the object. I suggest a new feature to support referencing an existing secret (and key) to fetch the admin password from. This would leave the users multiple options for generating/configuring the admin password. 

I would think a new structure could look like:
```yaml
spec:
  admin:
    user: my-admin # 1
    passwordSecretRef: # 2
      name: my-secret # 3
      key: artemis-pass # 4
    password: # 5
```

1. migrated field instead of `.spec.adminUser`
2. migrated field instead of `.spec.adminPassword`. Takes precedence over `.spec.admin.password` field if both are set
3. existing k8s secret managed by user, operator should fail reconciliation if secret is not found
4. secret key of users choosing. Defaults to `password` if not set
5. migrated field instead of `.spec.adminPassword`, ignored if `passwordSecretRef` is set, otherwise generate a password if not set

If we want to help with migration to new fields, we could keep the old fields as deprecated, and the new fields takes precedence over the old ones if the old are also set.

> [!TIP]
> Vote this issue reacting with :+1: or :-1:
