### ISSUE TITLE
Can not set expiryDelay greater than 24 days

### ISSUE THREAD

**Issue by olivierboudet** [arkmq-org/activemq-artemis-operator#1098]
**Describe the bug**
In `addressSetting` the type of `expiryDelay` is int32, so its max value is 2147483647.
As expiryDelay is milliseconds, it is not possible to set expiration to a value greater than around 24 days.

> [!TIP]
> Vote this issue reacting with :+1: or :-1:

**Comment by brusdev** [comment]
@olivierboudet the field `AddressSettings` is deprecated in favour of BrokerProperties. You can specify the address expiryDelay by using the broker properties, i.e.
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
spec:
  brokerProperties:
  - addressesSettings.my-address.expiryDelay=1382400000
```
