### ISSUE TITLE
ActiveMQArtemis CR OutOfSync, mismatched checksum on property file

### ISSUE THREAD

**Issue by john9x** [arkmq-org/activemq-artemis-operator#1116]
**Describe the bug**
The cluster deployed with config-bp secret 
```
apiVersion: v1
kind: Secret
metadata:
  name: config-bp
stringData:
  config.json: |
    {
      "addressSettings": { ... }
    ....
    }
```
Status of CR always OutOfSync
```
     Message:               out of sync on pod artemis-broker-ss-0, mismatched checksum on property file config.json, expected: 2594123130, current: 46476296. A delay can occur before a volume mount projection is refreshed.                                                                                                                                                                                                           
│     Reason:                OutOfSync                                                                                                                                                                                 │
│     Status:                False                                                                                                                                                                                     │
│     Type:                  BrokerPropertiesApplied
```
> [!TIP]
> Vote this issue reacting with :+1: or :-1:

**Comment by john9x** [comment]
Maybe related to #633 - I have addresses and queues with dots

**Comment by gtully** [comment]
can you paste in an example of the -bp secret content that causes the issue?

**Comment by john9x** [comment]
@gtully 
```
apiVersion: v1
kind: Secret
metadata:
  name: config-bp
stringData:
  config.json: |
    {
      "addressSettings": {
        "#": {         
          "maxDeliveryAttempts": 2,
          "redeliveryDelay": 10000,
          "maxRedeliveryDelay": 100000,
          "addressFullPolicy": "PAGE"
        },
        "server.push": {
          "maxDeliveryAttempts": 2
        },
        "server.email": {
          "maxDeliveryAttempts": 5
        }
      },
      "addressConfigurations": {        
        "server.push": {
          "routingTypes": "ANYCAST",
          "queueConfigs": {
            "navixy.server.push": {
              "routingType": "ANYCAST"
            }
          }
        },
        "navixy.server.email": {
          "routingTypes": "ANYCAST",
          "queueConfigs": {
            "navixy.server.email": {
              "routingType": "ANYCAST"
            }
          }
        }
      },
      "securityRoles": {
        "#": {
          "admin": {
            "createNonDurableQueue": true,
            "deleteNonDurableQueue": true,
            "createDurableQueue": true,
            "deleteDurableQueue": true,
            "createAddress": true,
            "deleteAddress": true,
            "consume": true,
            "browse": true,
            "send": true,
            "manage": true
          }
        },
        "emd.#": {
          "admin": {
            "createNonDurableQueue": true,
            "deleteNonDurableQueue": true,
            "createDurableQueue": true,
            "deleteDurableQueue": true,
            "createAddress": true,
            "deleteAddress": true,
            "consume": true,
            "browse": true,
            "send": true,
            "manage": true
          },
          "mqtt_device": {
            "createNonDurableQueue": true,
            "deleteNonDurableQueue": true,
            "createDurableQueue": true,
            "deleteDurableQueue": true,
            "createAddress": true,
            "deleteAddress": true,
            "consume": false,
            "browse": false,
            "send": true,
            "manage": false
          }
        }
      }
    }
```
Message:               out of sync on pod artemis-broker-ss-0, mismatched checksum on property file config.json, expected: 3352354407, current: 160423527.

**Comment by john9x** [comment]
From my tests the issue appears when configuration contains names with dots.

**Comment by john9x** [comment]
Also, this issue hides real problem: `addressFullPolicy` it's a mistake, must be `addressFullMessagePolicy`
without dotted names I see
Message:               some properties from config-bp resulted in error on pod artemis-broker-ss-0 : reasons: map[config.json:[{"value":"addressSettings.#.addressMessagePolicy=PAGE","reason":"java.lang.reflect.InvocationTargetException: No accessor method descriptor for: addressMessagePolicy on: class org.apache.activemq.artemis.core.settings.impl.AddressSettings"}]]

**Comment by gtully** [comment]
it seems the problem relates to the order in which json is mapped to properties and fed through the alder32 hash. The treatment of the dot results in a quoted key value, and that effects order!

**Comment by john9x** [comment]
@gtully 
IMHO

function SortedKeyValuePairsFromMap at activemqartemis_reconciler.go sorts properties after dotted keys were quoted meanwhile
org.apache.activemq.artemis.core.config.impl.ConfigurationImpl.InsertionOrderedProperties#loadJsonObject sorts no quoted keys

**Comment by john9x** [comment]
yeah. the issue is in sorting.
OK - quoting not changes sorting
```yaml
stringData:
  config.json: |
    {
      "addressSettings": {
        "a.a": {         
          "maxDeliveryAttempts": 2
        },
        "b.b": {
          "maxDeliveryAttempts": 2
        }
      }
    }
```

NOT OK - quoting changes sorting and `addressSettings."b.b".maxDeliveryAttempts=2` becomes before `addressSettings.a.maxDeliveryAttempts=2`
```yaml
stringData:
  config.json: |
    {
      "addressSettings": {
        "a": {         
          "maxDeliveryAttempts": 2
        },
        "b.b": {
          "maxDeliveryAttempts": 2
        }
      }
    }
```
