### ISSUE TITLE
Configure management.xml without ActiveMQArtemisSecurity

### ISSUE THREAD

**Issue by mbrozzo** [arkmq-org/activemq-artemis-operator#1127]
Hello, I need to enable JMX for the Datadog ActiveMQ integration. I noticed that in the default `management.xml` generated by the operator this line is commented:
```
   <!--<connector connector-port="1099"/>-->
```
According to [the docs](https://activemq.apache.org/components/artemis/documentation/latest/management.html#remote-jmx-access) I need that connector configuration in order to export JMS metrcis.

I noticed that the `ActiveMQArtemisSecurity` CR allows to do it, but it is deprecated and I could not find a way to do it using the `ActiveMQArtemis` CR or the `-jaas-config`. Am I missing something?

Thank you in advance!

> [!TIP]
> Vote this issue reacting with :+1: or :-1:

**Comment by gtully** [comment]
we may need to move the connector config from management.xml into the broker xml to fully support this use case or allow it to be configured via properties. short term, it is a good use case for the existing security cr to remain.

**Comment by gtully** [comment]
note in restricted mode, I want to avoid opening up rmi etc for jmx. the idea is that the prometheus jmx exporter agent can provide all required metrics and be locked down behind mtls. Do you know how well Datadog sits with the jmx_exporter?

see: https://github.com/arkmq-org/activemq-artemis-operator/issues/1128

**Comment by mbrozzo** [comment]
Hello @gtully, thank you for answering. I will continue using the CR then for the time being.

Datadog offers [an integration to scrape metrics from Prometheus endpoint](https://docs.datadoghq.com/containers/kubernetes/prometheus/?tab=kubernetesadv2), therefore I guess it is possible to use the JMX exporter. The nice thing of using JMX is that Datadog also offers an integration tailored to ActiveMQ Artemis' JMX metric, with a premade dashboard (and maybe other predefined stuff such as monitors, I still need to explore it). That convenience would probably be lost using the Prometheus integration.

**Comment by gtully** [comment]
sorry, I should have linked to the docs: resourceTemplate gives lots of options as it is essentially a patch, see: https://github.com/arkmq-org/activemq-artemis-operator/blob/main/docs/help/operator.md#custom-modifications-via-a-strategic-merge-patch

**Comment by mbrozzo** [comment]
@gtully I understand that exposing JMX directly with the appropriate security would be troublesome, I will not push for it. Anyways, I confirm that it is indeed possible to use the resourceTemplates to modify the management.xml file if one needs to expose JMX anyways.

Here is an example manifest based on the resources you provided:
```YAML
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: BROKER-NAME
spec:
  version: 2.40.0
  resourceTemplates:
    - selector:
        kind: "StatefulSet"
      patch:
        kind: "StatefulSet"
        spec:
          template:
            spec:
              initContainers:
                - name: "BROKER-NAME-container-init"
                  args:
                    - "-c"
                    - >-
                      /opt/amq/bin/launch.sh && /opt/amq-broker/script/default.sh &&
                      echo "Adding JMX configuration to management.xml" &&
                      sed -i 's|<management-context xmlns="http://activemq.apache.org/schema">|<management-context xmlns="http://activemq.apache.org/schema">\n   <connector connector-host="0.0.0.0" connector-port="1099" secured="false" />|' /amq/init/config/amq-broker/etc/management.xml

```

Furthermore, this method could also be used to import modularized XML configuration files, which has been requested in #160. I am sorry for going off-topic, but I want to take the opportunity to add that using the broker properties for configuration is much more difficult for first-time users as the ActiveMQ Artemis documentation is almost exclusively focused on the XML configuration, while configuration using broker properties requires reading the ActiveMQ Artemis source files.

The only downside of using this method is that if the operator's init image will be updated and will not use `/opt/amq/bin/launch.sh && /opt/amq-broker/script/default.sh` anymore as it's startup scripts, this manifest will need to be updated accordingly.

Thank you very much for the tip on resourceTemplates and for explaining the challenges with exposing JMX, I will close the issue now.
