### ISSUE TITLE
Configure brokerProperties  in the place of ActiveMQArtemisSecurity

### ISSUE THREAD

**Issue by Sirol90** [arkmq-org/activemq-artemis-operator#1134]
Hi,

How i can converter this **ActiveMQArtemisSecurity** to a valid **brokerProperties**?
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemisSecurity
metadata:
  name: artemis-security
  namespace: activemq-artemis-operator
spec:
  securitySettings:
    broker:
      - match: "#"
        permissions:
         - operationType: "createNonDurableQueue"
           roles:
             - "sender"
             - "receiver"
         - operationType: "send"
           roles:
             - "sender"
         - operationType: "createAddress"
           roles:
             - "receiver"
         - operationType: "consume"
           roles:
             - "receiver"
```

Thanks in advance,
Loris Montagna
