### ISSUE TITLE
Feature Request: Configuration of MessageLoadBalancingType through brokerProperties

### ISSUE THREAD

**Issue by akselkfklp** [arkmq-org/activemq-artemis-operator#1137]
**Describe the feature**
I would like to configure the messageLoadBalancingType of a cluster connection to STRICT to ensure messages are distributed across cluster nodes even without local consumers.

I assumed setting this under brokerProperties:
`clusterConfigurations.my-cluster.messageLoadBalancingType=STRICT`
would do the trick, but it doesnt take effect on the cluster.xml.

Steps to reproduce:
Deploy an ActiveMQArtemis CR with:
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
  namespace: my-namespace
spec:
  deploymentPlan:
    clustered: true
    size: 2
    persistenceEnabled: true
    messageMigration: true
  brokerProperties:
    - "clusterConfigurations.my-cluster.messageLoadBalancingType=STRICT"
```

Check the generated broker.xml in the pod:
`kubectl exec -it artemis-broker-ss-0 -n my-namespace -- cat /amq-broker/etc/broker.xml`

Observe that \<message-load-balancing\> under \<cluster-connection\> remains ON_DEMAND.
