### ISSUE TITLE
Cannot login to web console, but can you use user for the  broker

### ISSUE THREAD

**Issue by lambou123** [arkmq-org/activemq-artemis-operator#1150]
**Describe the bug**

I have this broker config

```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
  namespace: activemq-artemis-operator
spec:
  deploymentPlan:
    size: 3
    requireLogin: true
    persistenceEnabled: true
    messageMigration: false
    podSecurityContext:
      fsGroup: 0
  acceptors:
    - name: artemis
      bindToAllInterfaces: true
      protocols: all
      port: 61616
      sslEnabled: false
    - name: amqp
      bindToAllInterfaces: true
      protocols: amqp
      port: 5672
      sslEnabled: false
    - name: stomp
      bindToAllInterfaces: true
      protocols: stomp
      port: 61613
      sslEnabled: false
    - name: hornetq
      bindToAllInterfaces: true
      protocols: hornetq,stomp
      port: 5445
      sslEnabled: false
    - name: mqtt
      bindToAllInterfaces: true
      protocols: amqp
      port: 1883
      sslEnabled: false

```

and this secret:

```
apiVersion: v1
metadata:
  name: artemis-broker-credentials-secret
  namespace: default
kind: Secret
type: Opaque
stringData:
  AMQ_USER: admin
  AMQ_PASSWORD: adminPassword
  AMQ_CLUSTER_USER: cluster
  AMQ_CLUSTER_PASSWORD: clusterPassword

```
I can access the broker via cli with my credentials:
`
kubectl exec artemis-broker-ss-1 -- amq-broker/bin/artemis producer --user artemisx --password artemisy --url tcp://artemis-broker-ss-1:61616 --message-count=100
`

But i cannot access the web console with the credentials of AMQ_USER or AMQ_CLUSTER_USER via localhost:8161. 

- How can i configure the credentials for the webconsole to login?
 

> [!TIP]
> Vote this issue reacting with :+1: or :-1:
