### ISSUE TITLE
Configuration options not applied to cluster

### ISSUE THREAD

**Issue by dj-wasabi** [arkmq-org/activemq-artemis-operator#1160]
**Describe the bug**
Several configuration items like deploymentPlan, env are not applied at all in our cluster (test environment). The following manifest is used (generated by HELM):

```yaml
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-activemq
spec:
  acceptors:
    - name: tlsaccept
      protocols: all
      port: 61617
      sslEnabled: false
      needClientAuth: true
      expose: false
  deploymentPlan:
    size: 2
    messageMigration: true
    persistenceEnabled: true
    enableMetricsPlugin: true
    podDisruptionBudget:
      minAvailable: 1
    containerSecurityContext:
      runAsNonRoot: true
    storage:
      size: 10G
    extraVolumes:
      - name: jms-server-certs
        secret:
          secretName: artemis-active-secret
          defaultMode: 256
    extraVolumeMounts:
      - name: jms-server-certs
        mountPath: /etc/ssl/activemq
        readOnly: true
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: lifecycle
                operator: In
                values:
                  - OnDemand
  brokerProperties:
    - "metricsConfiguration.jvmGc=true"
    - "metricsConfiguration.jvmMemory=true"
    - "metricsConfiguration.jvmThread=true"
    - 'addressSettings.#.addressFullMessagePolicy=PAGE'
    - "connectorConfigurations.tlsaccept.params.sslEnabled=true"
    - "connectorConfigurations.tlsaccept.params.needClientAuth=true"
    - "connectorConfigurations.tlsaccept.params.keyStorePath=/etc/ssl/activemq/broker.ks"
    - "connectorConfigurations.tlsaccept.params.keyStorePassword=${KEYSTORE_PASSWORD}"
    - "connectorConfigurations.tlsaccept.params.trustStorePath=/etc/ssl/activemq/client.ts"
    - "connectorConfigurations.tlsaccept.params.trustStorePassword=${TRUSTSTORE_PASSWORD}"
  env:
    - name: KEYSTORE_PASSWORD
      valueFrom:
        secretKeyRef:
          key: keyStorePassword
          name: artemis-active-secret
    - name: TRUSTSTORE_PASSWORD
      valueFrom:
        secretKeyRef:
          key: trustStorePassword
          name: artemis-active-secret
```

But applying it in our cluster (we use Argo CD) it will deploy a very basic activemq (which will not become healthy), but misses lots of configuration.

Before "syncing", so it is fully clear what will be installed in our cluster:
![Image](https://github.com/user-attachments/assets/50bdff01-7356-4809-8804-2016f5326916)

After first (and many that followed) syncs (left side is configured in the cluster, right side is what we want to have applied from code):
![Image](https://github.com/user-attachments/assets/6eff2e29-1f4b-4c8e-98c6-6e6ec7e89cde)

The controller-manager does keep on providing errors in a full loop. But they are correct, as in the stateful-set does exist, just like the secret (this is a small copy of output, it keeps on looping. If more is needed, I happily provide these):
```
2025-05-16T08:59:27.393Z        ERROR   setup   Reconciler error        {"controller": "activemqartemis", "controllerGroup": "broker.amq.io", "controllerKind": "ActiveMQArtemis", "ActiveMQArtemis": {"name":"osgp-dlms-protocol-adapter-activemq","namespace":"mynamespace"}, "namespace": "mynamespace", "name": "osgp-dlms-protocol-adapter-activemq", "reconcileID": "02d75a91-c3fe-414e-b448-73de5d5c5c69", "error": "[\"failed to create new *v1.StatefulSet, statefulsets.apps \\\"artemis-activemq-ss\\\" already exists\"]"}
github.com/go-logr/logr.Logger.Error
        /opt/app-root/src/go/pkg/mod/github.com/go-logr/logr@v1.2.4/logr.go:299
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227
2025-05-16T08:59:27.408Z        ERROR   k8s_actions     Failed to create new *v1.StatefulSet    {"ActiveMQArtemis Name": "artemis-activemq-ss", "Namespace": "mynamespace", "error": "statefulsets.apps \"artemis-activemq-ss\" already exists"}
github.com/go-logr/logr.Logger.Error
        /opt/app-root/src/go/pkg/mod/github.com/go-logr/logr@v1.2.4/logr.go:299
github.com/arkmq-org/activemq-artemis-operator/pkg/resources.Create
        /opt/app-root/src/pkg/resources/k8s_actions.go:27
github.com/arkmq-org/activemq-artemis-operator/controllers.(*ActiveMQArtemisReconcilerImpl).createRequestedResource
        /opt/app-root/src/controllers/activemqartemis_reconciler.go:1602
github.com/arkmq-org/activemq-artemis-operator/controllers.(*ActiveMQArtemisReconcilerImpl).createResource
        /opt/app-root/src/controllers/activemqartemis_reconciler.go:1586
github.com/arkmq-org/activemq-artemis-operator/controllers.(*ActiveMQArtemisReconcilerImpl).ProcessResources
        /opt/app-root/src/controllers/activemqartemis_reconciler.go:1475
github.com/arkmq-org/activemq-artemis-operator/controllers.(*ActiveMQArtemisReconcilerImpl).Process
        /opt/app-root/src/controllers/activemqartemis_reconciler.go:189
github.com/arkmq-org/activemq-artemis-operator/controllers.(*ActiveMQArtemisReconciler).Reconcile
        /opt/app-root/src/controllers/activemqartemis_controller.go:182
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227
2025-05-16T08:59:27.408Z        ERROR   ActiveMQArtemisReconciler       error processing resources      {"error": "[\"failed to create new *v1.StatefulSet, statefulsets.apps \\\"artemis-activemq-ss\\\" already exists\"]"}
github.com/go-logr/logr.Logger.Error
        /opt/app-root/src/go/pkg/mod/github.com/go-logr/logr@v1.2.4/logr.go:299
github.com/arkmq-org/activemq-artemis-operator/controllers.(*ActiveMQArtemisReconcilerImpl).Process
        /opt/app-root/src/controllers/activemqartemis_reconciler.go:192
github.com/arkmq-org/activemq-artemis-operator/controllers.(*ActiveMQArtemisReconciler).Reconcile
        /opt/app-root/src/controllers/activemqartemis_controller.go:182
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227
2025-05-16T08:59:27.409Z        ERROR   setup   Reconciler error        {"controller": "activemqartemis", "controllerGroup": "broker.amq.io", "controllerKind": "ActiveMQArtemis", "ActiveMQArtemis": {"name":"osgp-dlms-protocol-adapter-activemq","namespace":"mynamespace"}, "namespace": "mynamespace", "name": "osgp-dlms-protocol-adapter-activemq", "reconcileID": "d4952ad3-638e-4bad-a384-e2206c800f19", "error": "[\"failed to create new *v1.StatefulSet, statefulsets.apps \\\"artemis-activemq-ss\\\" already exists\"]"}
github.com/go-logr/logr.Logger.Error
        /opt/app-root/src/go/pkg/mod/github.com/go-logr/logr@v1.2.4/logr.go:299
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227
2025-05-16T08:59:27.785Z        ERROR   k8s_actions     Failed to create new *v1.StatefulSet    {"ActiveMQArtemis Name": "artemis-activemq-ss", "Namespace": "mynamespace", "error": "statefulsets.apps \"artemis-activemq-ss\" already exists"}
github.com/go-logr/logr.Logger.Error
        /opt/app-root/src/go/pkg/mod/github.com/go-logr/logr@v1.2.4/logr.go:299
github.com/arkmq-org/activemq-artemis-operator/pkg/resources.Create
        /opt/app-root/src/pkg/resources/k8s_actions.go:27
github.com/arkmq-org/activemq-artemis-operator/controllers.(*ActiveMQArtemisReconcilerImpl).createRequestedResource
        /opt/app-root/src/controllers/activemqartemis_reconciler.go:1602
github.com/arkmq-org/activemq-artemis-operator/controllers.(*ActiveMQArtemisReconcilerImpl).createResource
        /opt/app-root/src/controllers/activemqartemis_reconciler.go:1586
github.com/arkmq-org/activemq-artemis-operator/controllers.(*ActiveMQArtemisReconcilerImpl).ProcessResources
        /opt/app-root/src/controllers/activemqartemis_reconciler.go:1475
github.com/arkmq-org/activemq-artemis-operator/controllers.(*ActiveMQArtemisReconcilerImpl).Process
        /opt/app-root/src/controllers/activemqartemis_reconciler.go:189
github.com/arkmq-org/activemq-artemis-operator/controllers.(*ActiveMQArtemisReconciler).Reconcile
        /opt/app-root/src/controllers/activemqartemis_controller.go:182
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227
2025-05-16T08:59:27.785Z        ERROR   ActiveMQArtemisReconciler       error processing resources      {"error": "[\"failed to create new *v1.StatefulSet, statefulsets.apps \\\"artemis-activemq-ss\\\" already exists\"]"}
github.com/go-logr/logr.Logger.Error
        /opt/app-root/src/go/pkg/mod/github.com/go-logr/logr@v1.2.4/logr.go:299
github.com/arkmq-org/activemq-artemis-operator/controllers.(*ActiveMQArtemisReconcilerImpl).Process
        /opt/app-root/src/controllers/activemqartemis_reconciler.go:192
github.com/arkmq-org/activemq-artemis-operator/controllers.(*ActiveMQArtemisReconciler).Reconcile
        /opt/app-root/src/controllers/activemqartemis_controller.go:182
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227
2025-05-16T08:59:27.794Z        ERROR   setup   Reconciler error        {"controller": "activemqartemis", "controllerGroup": "broker.amq.io", "controllerKind": "ActiveMQArtemis", "ActiveMQArtemis": {"name":"osgp-dlms-protocol-adapter-activemq","namespace":"mynamespace"}, "namespace": "mynamespace", "name": "osgp-dlms-protocol-adapter-activemq", "reconcileID": "02030e12-7968-490e-bf7c-2a8e3b772261", "error": "[\"failed to create new *v1.StatefulSet, statefulsets.apps \\\"artemis-activemq-ss\\\" already exists\"]"}
github.com/go-logr/logr.Logger.Error
        /opt/app-root/src/go/pkg/mod/github.com/go-logr/logr@v1.2.4/logr.go:299
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227
```

Details:
* Operator version: 2.0.2
* Kubernetes: 1.32

Any idea what is going wrong?

I do had to create a ClusterRole/Binding to get all kinds of (permission) errors solved that the controller-manager printed. This is what I added:

```
# clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: activemq-artemis-operator-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
---
# clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: activemq-artemis-operator-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: activemq-artemis-controller-manager
  namespace: mynamespace
roleRef:
  kind: ClusterRole
  name: activemq-artemis-operator-cluster-role
  apiGroup: rbac.authorization.k8s.io
```

FYI: I replaced the namespace and the name of the brokers to something generic.

> [!TIP]
> Vote this issue reacting with :+1: or :-1:
